# Generated by Django 4.2.7 on 2023-11-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100, verbose_name='специализация')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена')),
                ('visit', models.CharField(choices=[('primary', 'первичный прием'), ('secondary', 'повторный прием')], default='primary', max_length=20, verbose_name='прием')),
            ],
        ),
    ]
