# Generated by Django 4.2.7 on 2023-11-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_doctor_options_doctor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='visit',
            field=models.CharField(choices=[('первичный прием', 'первичный прием'), ('повторный прием', 'повторный прием')], default='первичный прием', max_length=20, verbose_name='прием'),
        ),
    ]
