# Generated by Django 4.2.7 on 2023-11-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_products_alter_cart_user_alter_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='итого'),
        ),
    ]
