# Generated by Django 4.2.7 on 2023-12-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_doctor_visit_alter_booking_is_booked'),
        ('cart', '0003_cartitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, through='cart.CartItem', to='main.labtest', verbose_name='анализы'),
        ),
    ]
